### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by Soduem** [vike256/Unibot#1]
Im assuming that im missing something for py https://cdn.discordapp.com/attachments/1112612408414961666/1159248906379599994/image.png?ex=653055ad&is=651de0ad&hm=7bc7fffcda5da42d5a1511cd1649c6dfbc8aff10d5c1f12421663f69b0275d24&
using pico 
flashing error.
a more thurough step by step would help 😄

**Comment by vike256** [comment]
Did you do any modifications the .ino file before uploading? And are you sure you completed these https://github.com/vike256/Unibot#raspberry-pi-pico-w-setup-for-arduino-ide

**Comment by vike256** [comment]
This might help: https://stackoverflow.com/questions/54087049/fatal-python-error-initfsencoding-unable-to-load-the-file-system-codec

**Comment by Soduem** [comment]
> Did you do any modifications the .ino file before uploading? And are you sure you completed these https://github.com/vike256/Unibot#raspberry-pi-pico-w-setup-for-arduino-ide

i changed the ssid and password thats about it, looking at the stackoverflow now.

**Comment by Soduem** [comment]
Same exact error, even redid the environment stuff

**Comment by Soduem** [comment]
> This might help: https://stackoverflow.com/questions/54087049/fatal-python-error-initfsencoding-unable-to-load-the-file-system-codec
am i missing something?? py version?? followed all steps aswell also using pico w

**Comment by vike256** [comment]
I haven't had any problems uploading the .ino to the board. Have you uploaded working Arduino code to your Pico W before? What versions are you using for Python and Arduino IDE?

**Comment by Soduem** [comment]
> I haven't had any problems uploading the .ino to the board. Have you uploaded working Arduino code to your Pico W before? What versions are you using for Python and Arduino IDE?


py 3.10.5 arduino 2.2.1

**Comment by Soduem** [comment]
and yes i have used software on it before

**Comment by Greetsew** [comment]
what version Arduino are you using @vike256

**Comment by Greetsew** [comment]
can you create a short video of you uploading it and all that so we can copy your exact steps?

**Comment by vike256** [comment]
> what version Arduino are you using @vike256

I am using the version 2.2.1 (latest).



> can you create a short video of you uploading it and all that so we can copy your exact steps?

Probably will someday but I don't have time right now. From what I saw in your issue #3 (Board not connected), your problem could be that you haven't selected the right com port. Go to _Arduino IDE > Tools > Port_ and try a different port.

**Comment by Greetsew** [comment]
![image](https://github.com/vike256/Unibot/assets/123421084/8fe30af0-d92f-4d35-b867-3a177a1a7b74)
there are no ports for me

**Comment by Greetsew** [comment]
i think i got it, was a faulty cable

**Comment by vike256** [comment]
> i think i got it, was a faulty cable. so now i have com3 port but, still the normal error (Multiple libraries were found for "Mouse.h")

That's not a problem if it does not say error. It just selects one of the libraries automatically. The red text can be quite misleading in Arduino IDE.

**Comment by Greetsew** [comment]
so that means it worked?

**Comment by Greetsew** [comment]
oh i did thank you very much. i can make a video for your yt if you want?

**Comment by vike256** [comment]
> oh i did thank you very much. i can make a video for your yt if you want?

Feel free to do so. You can link it to this issue.

**Comment by Greetsew** [comment]
ok so it registers the colors but doesnt actully do the mouse mouvement

**Comment by vike256** [comment]
> ok so it registers the colours but doesn't actually do the mouse movement

Hey, I'm closing this issue. Can you open another one with more details discussing your current issue?
