### ISSUE TITLE
Mouse not actually moving, raspberry pi pico w

### ISSUE THREAD

**Issue by wpngy** [vike256/Unibot#10]
Same as the other issues opened here, prints move, but doesnt actually move.

**Comment by vike256** [comment]
Not enough information.
https://github.com/codeforamerica/howto/blob/master/Good-GitHub-Issues.md

**Comment by wpngy** [comment]
#### Description
It works perfectly when valorant is closed, but when i open it, it seems like it starts blocking movement

#### Screenshots
![image](https://github.com/codeforamerica/howto/assets/96589377/213cb663-9199-46b2-9dd5-53f34ed0906e)

**Comment by vike256** [comment]
So it works in other games but stops working in valorant? You are using socket with what board?

**Comment by wpngy** [comment]
I haven't tried on any other game, its just it starts moving on a image. But when my valorant is opened, it just doesnt do anything. Just prints, im using socket with raspberry pi pico w

**Comment by vike256** [comment]
So it prints the details with the received ACK but it does not actually move the mouse? I would try testing on some other game like an aim trainer.

**Comment by wpngy** [comment]
It seemed to work on a online aim trainer, but i think vanguard is blocking its movement
