### ISSUE TITLE
Upload error, Stuck on 'Connecting...', Can't find IP

### ISSUE THREAD

**Issue by Greetsew** [vike256/Unibot#2]
I did everything the setup says but its not running. im using raspberry pi pico w.
![image](https://github.com/vike256/Unibot/assets/123421084/a885622d-a89f-49e0-97d5-128b98ab916c)
![image](https://github.com/vike256/Unibot/assets/123421084/74f5de3d-fcca-41ce-992a-cfebcfa60433)
wifi login is also filled out

**Comment by vike256** [comment]
Upload it through the Arduino IDE

**Comment by Greetsew** [comment]
![image](https://github.com/vike256/Unibot/assets/123421084/3ba37891-404f-4cb0-a4b9-35146b7d9728)

this is what i get from verifying and and uploading 
![image](https://github.com/vike256/Unibot/assets/123421084/ae937cce-2457-4232-a40d-47c9baad2a27)
this is what i get when debuging

**Comment by Greetsew** [comment]
ok so i didnt see the new libs u added then when i ran the bat i got this 
![image](https://github.com/vike256/Unibot/assets/123421084/8d63c834-a531-4cae-b057-916fbcd75ada)

**Comment by vike256** [comment]
Is your pc and pico connected to the same network? Also try going to your network adapter settings in Windows and enabling sharing from adapter properties.

**Comment by Greetsew** [comment]
can you give me the steps to connect so ik i did it right

**Comment by Greetsew** [comment]
can you show me how to find picos ip?

**Comment by Greetsew** [comment]
can we talk on discord abt it so its easier ill send you a email of my discord

**Comment by vike256** [comment]
Any issue is good to solve on GitHub so other users can find the solutions.

**Comment by Greetsew** [comment]
can you show me how to get the ip of the pico

**Comment by vike256** [comment]
Go to your Wi-Fi hotspot/router settings and you should see a list of devices and ther IPs

**Comment by Greetsew** [comment]
![image](https://github.com/vike256/Unibot/assets/123421084/40d3090e-6510-489e-a151-8e5d6d27e144)
Here?

**Comment by vike256** [comment]
Try using 2.4 GHz if the Pico is not able to connect. That's what I am using.

**Comment by Greetsew** [comment]
ok ill try real quick

**Comment by Greetsew** [comment]
ye i got the right ip

**Comment by Greetsew** [comment]
but it still wont connect
