### ISSUE TITLE
How to do it work for no hardware

### ISSUE THREAD

**Issue by 1godrrty** [vike256/Unibot#23]
How to do it work for no hardware , I already install Interception driver and type none it not work

**Comment by vike256** [comment]
Communication type should be set to `driver` when using interception driver.

**Comment by 1godrrty** [comment]
> Communication type should be set to `driver` when using interception driver.

not work idk why

**Comment by vike256** [comment]
Can't help with just that information. The driver versions works just fine for me. I tested it on a fresh install and no problems.
