### ISSUE TITLE
Question about 2 mic inputs?

### ISSUE THREAD

**Issue by 0xFFD** [vike256/Unibot#26]
Most Anti-Cheats block 2 mic inputs, I want to use Leonardo + Ethernet host shield but I'm worried about the Arduino inputs will get blocked. Any information or comment about that? And are you using any clone hardware?

**Comment by vike256** [comment]
> Most Anti-Cheats block 2 mic inputs, I want to use Leonardo + Ethernet host shield but I'm worried about the Arduino inputs will get blocked. Any information or comment about that? 
The Unibot project does not account for anti-cheat bypassing. Closing issue.

> And are you using any clone hardware?
My Leonardo is from KEYESTUDIO
My Pico W is from FREENOVE
