### ISSUE TITLE
How

### ISSUE THREAD

**Issue by 1godrrty** [vike256/Unibot#27]
How to setup config for interception driver , I try it a lot of time But it's not working.

**Comment by vike256** [comment]
What is not working? Did you correctly install the driver and Unibot's python requirements?

**Comment by 1godrrty** [comment]
> What is not working? Did you correctly install the driver and Unibot's python requirements?
> To fix an error we need to see the error message with enough context provided.

It not have error message , I set type to driver and run ,press f2 but it not work ,I install driver like this video https://youtu.be/oJGQbK6iYLM?si=NRMmP1QxC3H0Xrps

**Comment by 1godrrty** [comment]
> What is not working? Did you correctly install the driver and Unibot's python requirements?
> To fix an error we need to see the error message with enough context provided.

I tried the arduino with unibot. It worked great.

**Comment by 1godrrty** [comment]
> > > What is not working? Did you correctly install the driver and Unibot's python requirements?
> > > To fix an error we need to see the error message with enough context provided.
> > 
> > 
> > It not have error message , I set type to driver and run ,press f2 but it not work ,I install driver like this video https://youtu.be/oJGQbK6iYLM?si=NRMmP1QxC3H0Xrps
> 
> So both the aim and triggerbot don't work with the driver? That's a 14 minute video. Are you sure you installed the driver by downloading the latest release and running the command line installer with the argument `/install`. And after that rebooted of course.
> 
> And what game are you testing this on? Some games may block the input...

I'm sure I installed the latest driver. I test on valorant

**Comment by vike256** [comment]
> I test on valorant

I'm pretty sure that might be the issue. Valorant's anti-cheat blocks various types of inputs.
