### ISSUE TITLE
force close

### ISSUE THREAD

**Issue by 1godrrty** [vike256/Unibot#29]
it force close sometime when i play on valorant

**Comment by vike256** [comment]
No sufficient information. Could be anything.

**Comment by 1godrrty** [comment]
> Not sufficient information. The issue could be anything.

I usually play no trouble.just got into trouble three days ago When I played it on valorant , it suddenly shut down by it self.

**Comment by vike256** [comment]
> I usually play no trouble.just got into trouble three days ago When I played it on valorant , it suddenly shut down by it self.

So it's not a recurring issue? Maybe you accidentally pressed F4 which is the exit key?

**Comment by 1godrrty** [comment]
> > I usually play no trouble.just got into trouble three days ago When I played it on valorant , it suddenly shut down by it self.
> 
> So it's not a recurring issue? Maybe you accidentally pressed F4 which is the exit key?

I'm pretty sure I didn't press the f4 button.

**Comment by vike256** [comment]
Is this a recurring issue and if it is can you provide the console output?

**Comment by 1godrrty** [comment]
> Is this a recurring issue and if it is can you provide the console output?

what do you mean? i not sure

**Comment by vike256** [comment]
> what do you mean? i not sure
Do you have this issue frequently or was this a one time thing?

**Comment by 1godrrty** [comment]
> > what do you mean? i not sure
> 
> Do you have this issue frequently or was this a one time thing?

This problem is very frequent.I try to not chang any code But it force close by itself  again.

**Comment by vike256** [comment]
Can you post the error message?

**Comment by 1godrrty** [comment]
wait i will try your new update again.

**Comment by RAPatekgenah** [comment]
It should working with lastest build. Try it

**Comment by 1godrrty** [comment]
> It should working with lastest build. Try it

It's usable but not as good at locking targets as the old version.

**Comment by 1godrrty** [comment]
> Can you post the error message?

it not have a error message.I've tried it several times. i don't need to use a lastest version because it not as good at locking targets.can you edit the lastest version to have a good aimbot like the old version?

**Comment by vike256** [comment]
> it not have a error message.I've tried it several times. i don't need to use a lastest version because it not as good at locking targets.can you edit the lastest version to have a good aimbot like the old version?

What do you mean? Both target detection and aiming have remained relatively same between updates.

**Comment by vike256** [comment]
Issue is invalid because the user is not using the latest version. Closing.
