### ISSUE TITLE
Arduino IDE Errors w/ Raspberry pi pico w

### ISSUE THREAD

**Issue by Greetsew** [vike256/Unibot#3]
![image](https://github.com/vike256/Unibot/assets/123421084/3a189dba-f812-4ae9-9e99-1c3a81fcd966)
![image](https://github.com/vike256/Unibot/assets/123421084/0ce6d55a-5826-4294-b747-a6af0d1d0679)

im getting this error when trying to upload

also says 
![image](https://github.com/vike256/Unibot/assets/123421084/2ff7c20d-2471-4e74-a474-02ce831d013d)
but its plugged in

**Comment by vike256** [comment]
Duplicate of #1
