### ISSUE TITLE
Aimbot being sloppy

### ISSUE THREAD

**Issue by zouyys** [vike256/Unibot#32]
Hm, your latest version of unibots aimbot has been feeling a little sloppy... Ive tried playing with many different configs and stuff but it still seems to be very delayed and robot like.

**Comment by zouyys** [comment]
Every other versions aimbot was nice and very fast compared to this one

**Comment by vike256** [comment]
Depends on your input type and config. Is your smoothness, speed or fps too high in the config?

**Comment by vike256** [comment]
Can you share your config settings and attach a video of the aiming?

**Comment by vike256** [comment]
Closing, inactive.
