### ISSUE TITLE
The game screen is not captured

### ISSUE THREAD

**Issue by Sunnnner** [vike256/Unibot#35]
I used serial with Rasberry Pi Pico， The mouse moved correctly when I tested it in some games or on the desktop，But in some games, it doesn't capture the game, why is that, is there another setting that can solve it? How about using obs to read the screen and then move the mouse?

**Comment by SaD1ct** [comment]
This functionality is necessary to avoid getting a color screen ban.  window_title_search=Fullscreen Projector (Source)

**Comment by vike256** [comment]
I'll look into adding window capture tomorrow since I am busy today. Thanks for the report.

**Comment by vike256** [comment]
For now I wont be doing window capture. We'll see if this becomes a bigger problem and adjust as needed.
