### ISSUE TITLE
mouse moving randomly

### ISSUE THREAD

**Issue by RAPatekgenah** [vike256/Unibot#36]
i attached video
the issues : when i use rapidfire, or i just aiming fire make mouse moving randomly by itself

https://github.com/vike256/Unibot/assets/48162247/b47e0924-dc67-463e-900e-e6d52f079752

**Comment by vike256** [comment]
Good morning, I am investigating this issue. Hope I get it fixed today but I am quite busy with schoolwork.

**Comment by RAPatekgenah** [comment]
tested and working excellent. thanks.
