### ISSUE TITLE
Dxcam Suggestion

### ISSUE THREAD

**Issue by slslazy** [vike256/Unibot#38]
Have you considered adding device_idx=0 and output_idx=0 when you create dxcam? Incorporating in config might be a good idea too. I'm guessing there are a few "doesn't work with my monitor" complaints. Sorry on phone otherwise I'd pull.

**Comment by vike256** [comment]
I've seen only one report of dxcam not working and it was fixed by just switching to mss in the config. Good idea but I don't intend to implement it for now. We'll see if this gets implemented in the future.
