### ISSUE TITLE
Unibot continues to be fantastic, and there's something else we want

### ISSUE THREAD

**Issue by Kaira3535** [vike256/Unibot#40]
**Can you include an adjustable smart AI logic in Unibot again? For instance, if I were to give an example, for use in a game like CS2, config, etc. If you can do this, it would really be excellent.**

![image](https://github.com/vike256/Unibot/assets/76821732/7d323e77-38aa-4759-a294-eaf7cefc8656)
![image](https://github.com/vike256/Unibot/assets/76821732/9d050301-9ba5-4aee-81df-d44849339bba)

**Comment by Mosyexp** [comment]
that would make unibot on spar with paid hacks or rootkit, which would be superior, would love to see it implemented!

**Comment by Kaira3535** [comment]
> that would make unibot on spar with paid hacks or rootkit, which would be superior, would love to see it implemented!

I am definitely waiting for a smart ai, I hope it does smart ai, that is, a scenario made with yolo, but if it can be done without model training, I think it can give excellent results.

**Comment by vike256** [comment]
This is outside the scope of Unibot.

**Comment by Kaira3535** [comment]
> This is outside the scope of Unibot.
> 
> Unibot is just a colorbot.

so are you planning to share a smart ai with yolov8n we would really appreciate it because you are really doing this very well
_?
