### ISSUE TITLE
SMART AI

### ISSUE THREAD

**Issue by Kaira3535** [vike256/Unibot#41]
so are you planning to share a smart ai with yolov8n we would really appreciate it because you are really doing this very well

_??

**Comment by vike256** [comment]
> so are you planning to share a smart ai with yolov8n we would really appreciate it because you are really doing this very well
> 
> _??

You already made a post about this and I answered no. This has nothing to do with Unibot.

I barely have the time to develop Unibot itself. Just a reminder I am doing this for free. For further development on Unibot and on any of my future projects, consider donating.
