### ISSUE TITLE
Aiming between 2 enemies

### ISSUE THREAD

**Issue by querleyz** [vike256/Unibot#42]
fixed

**Comment by vike256** [comment]
Try to see in debug display with mode mask. It's probably combining the enemies into one shape.

**Comment by vike256** [comment]
Don't know if that's really something that can be reasonably fixed. Using pixel detection is an option

**Comment by vike256** [comment]
> > Don't know if that's really something that can be reasonably fixed. Using pixel detection is an option
> 
> In Pixel Detection, it does not align exactly to the head, sometimes to the body, sometimes to the head. Not stable. DXcam and MSS both same.

It aims at the nearest pixel that is in the target color range. Might not work very well in games where only the outlines are the target color.

**Comment by Mosyexp** [comment]
the potential fix for this is decreasing head detection by adding a head size to config, that will lower the head size when bot sees it and fixes the merge
