### ISSUE TITLE
Uno r4 wifi does not support uploading wifi images

### ISSUE THREAD

**Issue by kimiboby** [vike256/Unibot#43]

**Comment by vike256** [comment]
?

**Comment by kimiboby** [comment]
> ?
The arduino uno R4 wifi does not support wifi.ini

**Comment by vike256** [comment]
I'll have a look if when I get enough donations to buy the Uno R4. Can't really have support for it if I can't test it.

**Comment by vike256** [comment]
Further development isn't planned. I'll keep this in mind as an potential update if I regain interest in this project.
