### ISSUE TITLE
connection

### ISSUE THREAD

**Issue by exotxc** [vike256/Unibot#44]
I'm using an arduino leonardo with ethernet. Followed all the steps but I got the error "Could not connect (Socket). [WinError 10061] No connection could be made because the target machine actively refused it." Any ideas? Is it because I may have entered the ip address or mac addresses wrong? Not sure how to find the mac address.

**Comment by vike256** [comment]
Wrong IP. Enter the IP of the Arduino, not your router or any other device it's connected to.
