### ISSUE TITLE
Error when using -DCDC_DISABLED to hide COM port.

### ISSUE THREAD

**Issue by umerdaed** [vike256/Unibot#45]
I followed the instructions to change board PID & VID for my arduino leonardo, but if I use -DCDC_DISABLED to remove the COM port I get the following error when I try to upload: 

C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o: In function `timedRead':
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:34: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:34: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:34: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:34: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:36: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o:C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:36: more undefined references to `Serial' follow
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o: In function `setup':
D:\UniBot\Unibot-main\src\serial/serial.ino:45: undefined reference to `Serial_::begin(unsigned long)'
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o: In function `setTimeout':
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:89: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:89: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:89: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Stream.cpp:89: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o: In function `write':
C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Print.h:54: undefined reference to `Serial'
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o:C:\Users\umar\AppData\Local\Arduino15\packages\arduino\hardware\avr\1.8.6\cores\arduino/Print.h:54: more undefined references to `Serial' follow
C:\Users\umar\AppData\Local\Temp\ccDHIZ9r.ltrans0.ltrans.o: In function `loop':
D:\UniBot\Unibot-main\src\serial/serial.ino:83: undefined reference to `Serial_::flush()'
collect2.exe: error: ld returned 1 exit status
Multiple libraries were found for "Mouse.h"
  Used: C:\Users\umar\Documents\Arduino\libraries\Mouse
  Not used: C:\Users\umar\AppData\Local\Arduino15\libraries\Mouse
exit status 1

Compilation error: exit status 1

I get no errors when I follow the commands without disabling the COM port and am able to compile properly. Also even if I do manage to hide the COM port, how would I tell the config.ini to communicate over HID? since the only option over serial is to include a COM port which would be disabled.

**Comment by vike256** [comment]
Hey,

I am just going to close this as this isn't a problem with Unibot. I've never had to disable the COM-port, because it only concerns people who want to avoid anticheat. I'm sure there are better communities out there to answer this question.
