### ISSUE TITLE
ethernet shield

### ISSUE THREAD

**Issue by isvktt** [vike256/Unibot#49]
work in arduino + ethernet shield ?

**Comment by Ahmo9345** [comment]
Yes it will work you have to go to config open it in notepad. After opening there will be communication.
[communication]
type = none
encrypt = false
ip = 0.0.0.0
port = 50124
com_port = COM1
Just like this change type = none, to type = ethernet, put your ip, put the port, select the COM_PORT remember com port and port are different port if for your network and com_port is for the communication between audrino and your pc. Thats it after doing this it will work HOPEFULLLY  👍
