### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Axeousss** [vike256/Unibot#53]
I am trying to install this as a non english speaker and a non coder/programmer and it is very confusing,could you please make a installation tutorial on youtube or something like that? Would be really helpful

**Comment by vike256** [comment]
Seems like you want to use this project to cheat in a video game. I won't assist you since this project is made for educational purposes only. 

The code is there and the guide is comprehensive. Use those as learning material and you're free to build whatever you want.
