### ISSUE TITLE
Pi Pico W

### ISSUE THREAD

**Issue by Agis0** [vike256/Unibot#58]
Hello there,

I was searching up for more information about usage of Pi Pico W. I saw that most people use arduino for cheating. Is it working for Pi Pico W? Is it detected by Vanguard with Pi Pico W?

Sincerely,
Agis0

**Comment by vike256** [comment]
Unibot works with Pico W. Avoiding anti-cheat is unrelated to this project.

**Comment by maropboia** [comment]
> Hello there,
> 
> I was searching up for more information about usage of Pi Pico W. I saw that most people use arduino for cheating. Is it working for Pi Pico W? Is it detected by Vanguard with Pi Pico W?
> 
> Sincerely, Agis0

I'm experimenting on bypass anti cheat with arduino but i can't find enough source code of cheats with arduino for project . Can you help by sharing what you know?
