### ISSUE TITLE
not working with rp2040

### ISSUE THREAD

**Issue by jammesop007aha** [vike256/Unibot#63]
showing no hid library. and please make a tutorial to a to z show everything

**Comment by vike256** [comment]
No thanks. Ask lazy questions, get lazy answers.

**Comment by vike256** [comment]
All guides have been provided in the wiki. Start from there.

**Comment by jaiwiwjwjwisn** [comment]
> All guides have been provided in the wiki. Start from there. As this is a cheating script in a sense, I don't find it desirable to spend my time helping people use it. I would prefer people to use this project as a learning opportunity.



> All guides have been provided in the wiki. Start from there. As this is a cheating script in a sense, I don't find it desirable to spend my time helping people use it. I would prefer people to use this project as a learning opportunity.

Brother i have one pi pico Chinese clone 16MB flash memory version, and I'm using arduino cloud (ide in internet) how to setup board manager for using unibot?
