### ISSUE TITLE
Add support for usb rubber ducky aka attiny85 

### ISSUE THREAD

**Issue by jaiwiwjwjwisn** [vike256/Unibot#64]
Usb rubber ducky is powerful hid device. And digispark made a cheap 3$ one, please make code for this too.

**Comment by vike256** [comment]
Haven't heard of that device before. Googled a bit and seems like it doesn't have any native method of communication with the PC such as a serial port. Would be quite a hassle to implement as this is just a hobby project and I don't have the device. Feel free to fork the project and modify it to your liking if you find a convenient way to add support for the device.

**Comment by jaiwiwjwjwisn** [comment]
Maybe you don't have to change all, just needed to find a method to communicate with pc.
