### ISSUE TITLE
Not an issue.

### ISSUE THREAD

**Issue by jaiwiwjwjwisn** [vike256/Unibot#66]
Brother i have one pi pico Chinese clone 16MB flash memory version, and I'm using arduino cloud (ide in internet) how to setup board manager for using unibot? (This project is great and i starred ♥️)

**Comment by vike256** [comment]
Haven't heard of Arduino Cloud before. I recommend using the actual Arduino IDE and following the guide.
https://github.com/vike256/Unibot/wiki/Guide
