### ISSUE TITLE
My screen capture cannot be opened properly, but without using debug, the mouse can follow the target's movement on aimlab

### ISSUE THREAD

**Issue by toutie1** [vike256/Unibot#67]
Hi,broI have installed the required libraries for the requirements,but in debug,enabled and always on can be used simultaneously，Unable to function properly.How should we handle the situation where screen capture will not respond if it is executed separately as enabled.My computer version is Win11, The ptyton version is 3.12
![4e935bfad17a231c4c854780a6c2d98](https://github.com/vike256/Unibot/assets/170751007/a8157266-d832-4600-9321-002d87b68753)
![8d95806d1845e61e41647047bd4d450](https://github.com/vike256/Unibot/assets/170751007/0561b569-1b04-4ce4-bbc4-c4df1d61500b)

**Comment by RAPatekgenah** [comment]
Check your config. Change to mss if you have problem with dxcam.

**Comment by vike256** [comment]
Not sure about this issue but it should no longer exist since Unibot is using BetterCam now. Open another issue if it persists.
