### ISSUE TITLE
Could it be possible to add support for USB HOST, so that they can communicate in the way of hID instead of the com port

### ISSUE THREAD

**Issue by SHENZHENGG** [vike256/Unibot#69]
Yes, I've been trying to make it too. INO file to make unibot use USB HOST, but I never did. What comes to mind is to use the hid way to connect, so that the COM port can be shielded. If you are willing to make I can pay you please send me your contact details

**Comment by RAPatekgenah** [comment]
Add me dc. Raflyfb.  I’ll guide you

**Comment by vike256** [comment]
Would be an interesting feature but as this is designed to be an "universal" script it would be quite a challenge to implement USB Host Shield support to every mouse.

**Comment by vike256** [comment]
But to my knowledge you don't need an USB Host Shield to use HID communication with the microcontroller.
