### ISSUE TITLE
Fatal Python error: initfsencoding: unable to load the file system codec

### ISSUE THREAD

**Issue by Soduem** [vike256/Unibot#7]
As I already made the same issue yesterday I assume you know the error? https://cdn.discordapp.com/attachments/1112612408414961666/1159248906379599994/image.png?ex=653055ad&is=651de0ad&hm=7bc7fffcda5da42d5a1511cd1649c6dfbc8aff10d5c1f12421663f69b0275d24&
(i also updated to the latest python vers)
com3 port everything connected no problems connecting not a fault cable aswell.
if its important yes, I'm trying to spoof my board.
my last issue was closed while I was sleeping

**Comment by vike256** [comment]
Can't really help you since I haven't had any problems with uploading. My google searches for this issue don't bring up related information. I'm going to leave the issue open.

**Comment by Soduem** [comment]
so i think i have it fixed? but which one do i select to be sure i did 
![image](https://github.com/vike256/Unibot/assets/92614972/ed708549-4506-4c0a-a200-b770238e4193)

**Comment by vike256** [comment]
Select the board you are using. Pico and Pico W are different products.
