### ISSUE TITLE
windows 10 issue

### ISSUE THREAD

**Issue by jammesop007aha** [vike256/Unibot#70]
I can not fix 
C:\Windows\system32>install-interception.exe

Interception command line installation tool
Copyright (C) 2008-2018 Francisco Lopes da Silva

usage: install-interception.exe [/install | /uninstall]

C:\Windows\system32>install-interception.exe/install

Interception command line installation tool
Copyright (C) 2008-2018 Francisco Lopes da Silva

Could not write to \system32\drivers

C:\Windows\system32>                   windows 10

**Comment by vike256** [comment]
Issue not related to Unibot, closing.
