### ISSUE TITLE
Mouse mouvement dont work

### ISSUE THREAD

**Issue by Nexize45** [vike256/Unibot#77]
I installed everything as instructed: color detection is working, and everything else seems to be functioning correctly. However, when I press the keys to activate the aimbot or other actions, they don't work. The only actions that respond are key_exit and key_reload_config. I suspect the issue might be related to mouse drivers. I've tried both WinAPI and Interception, but neither worked, and I prefer not to use an Arduino. I even asked ChatGPT for help, but it couldn't solve the issue.

Recap: When I run main.py, color detection works, but the inputs don't respond.

![image_2024-10-25_211237156](https://github.com/user-attachments/assets/06c5d416-23f9-4d88-99ab-d825767605c6)
![image_2024-10-25_211313365](https://github.com/user-attachments/assets/1b67257d-fbfa-4f83-90f1-bf3d1a184979)
![image_2024-10-25_211333702](https://github.com/user-attachments/assets/66205679-3d90-4d55-a316-f3ed5361cdfb)

pls someone help me

**Comment by vike256** [comment]
https://github.com/vike256/Unibot/wiki/FAQ-and-troubleshooting-tips#i-cant-get-it-to-work

**Comment by Nexize45** [comment]
i tried on aimlab too and it doesnt work

**Comment by LuckQoo** [comment]
Is there any chance—is there any chance—that you didn't press F2 and F3?
